### ISSUE TITLE
As an documentation writer for ODH, I want to have a tutorial on how to setup bdp-core to add documentation to the swagger interfaces.

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/documentation#2]
How to setup STS (eclipse)
How to setup Pivotal server inside STS
How to import core files and web services
How to launch them
Which files must be changed for any Swagger annotations?

Could be put into our flight rules.

**Comment by Piiit** [comment]
@stefanodavid @ohnewein I think this issue is deprecated, since we have a quickbuild script now and the rest can be read from online sources, swagger documentation etc.... OK?

**Comment by stefanodavid** [comment]
@Piiit I quite agree -  the part about STS/eclipse setup however is missing, though I think it should not be a big deal for a developer.

**Comment by Piiit** [comment]
Maybe we could just add that with some useful links about getting started with STS or Eclipse, one annotation to some REST calls. However, the first part is generic and should be put in a common "First steps as core developer" section, and the second could be a small paragraph inside that main chapter. What do you think, @stefanodavid ?

**Comment by stefanodavid** [comment]
About STS: I think that a developer should know how to setup an IDE, so probably this part could be very very short (little text +1-2 screenshots, which I already have.

About the second point, since together with @bertolla we decided to introduce the (new) annotations to V2. I already wrote a sample one, that I will check after a stable version of V2 has been done.  I suggest that we now close this issue (and issue 17 in odh-docs), and discuss this at that point. Would that be a good solution for you, @Piiit?

**Comment by Piiit** [comment]
@stefanodavid 
I agree. Just add a little text with links to Eclipse and STS installation and tomcat/pivotal setup, import of bdp-core project and run it, to see a first output inside a browser. You could maybe take the curl examples from bdp-core/quickbuild.sh as a minimal trial... 
Finally, a little paragraph about swagger annotations and where to put them inside bdp-core. 
OK?

**Comment by Piiit** [comment]
BTW, why close unresolved issue and open them as new issue later again? Why not just keep them open?
